version: '3'
services:
  limesurvey:
    
    image: docker.io/martialblog/limesurvey:latest
    
    restart: always
     
    # save uploads of surveys to mount on host system
    volumes:
     - ~/LimeSurvey/upload/surveys:/var/www/html/upload/surveys 

    environment:
      - DB_TYPE=pgsql
      - DB_PORT
      
      # here set host to AWS Postgresql
      - DB_HOST

      - DB_PASSWORD
      - DB_NAME
      - DB_USERNAME
      - ADMIN_USER
      - ADMIN_NAME
      - ADMIN_PASSWORD
      - ADMIN_EMAIL
      - PUBLIC_URL
    
    
    ports:
      - 8080:8080

volumes:
  limesurvey:
  db-data:
